"""Validate and export the emergency center-bolt idler in the source arm CAD.

This performs a geometric rotation sweep, not a stress or bearing-life analysis.
The source HN11-I101 idler, cap, and center screw are removed from the check
assembly and replaced by the printed adapter plus a reference wide M3 washer.

Run:
    uv run python studies/xl430_lowcost/validate_emergency_idler.py --fail-on-mismatch
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cadquery as cq
from OCP.BRepAdaptor import BRepAdaptor_Surface

from cadre import PartIntent


_HERE = Path(__file__).resolve()
_STUDY = _HERE.parent
_CADRE_ROOT = _HERE.parents[2]
_REPO = _HERE.parents[4]
_ASSEMBLY_IO = _CADRE_ROOT / "studies" / "follower_geometry_revision" / "source"
for path in (_STUDY, _STUDY / "parts", _ASSEMBLY_IO):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from assembly_io import bounds, read_step  # noqa: E402
import emergency_center_bolt_idler as model  # noqa: E402


DEFAULT_ASSEMBLY = _REPO / "hardware" / "follower" / "step" / "arm.step"
DEFAULT_OUT = _CADRE_ROOT / "outputs" / "prototypes" / "emergency_center_bolt_idler"
LINK_PATH = "/Robot Arm v14/XL430 to XL330 new connector v6:1/connector:1"
MOTOR_PREFIX = "/Robot Arm v14/XL-430_new v1:2/"
IDLER_NAME = "DC11_A01_IDLER_DUMMY:1"
REPLACED_TOKENS = ("IDLER_DUMMY", "IDLER_CAP", "IDLER_SCREW")
VOLUME_TOL_MM3 = 1.0e-6


def _unique(rows, predicate, description):
    matches = [row for row in rows if predicate(row)]
    if len(matches) != 1:
        raise RuntimeError(f"expected one {description}; found {len(matches)}")
    return matches[0]


def _volume_intersection(a: cq.Shape, b: cq.Shape) -> float:
    return float(a.intersect(b).Volume())


def _axis_cylinders(shape, y, z, bore):
    """Measure trimmed coaxial cylinders, distinguishing bores from bosses."""
    matches = []
    for face in shape.Faces():
        if face.geomType() != "CYLINDER":
            continue
        surface = BRepAdaptor_Surface(face.wrapped)
        cylinder = surface.Cylinder()
        p = cylinder.Location()
        if abs(cylinder.Axis().Direction().X()) < 0.999999:
            continue
        if abs(p.Y() - y) > 1e-5 or abs(p.Z() - z) > 1e-5:
            continue
        # A reversed face is not necessarily a bore: the underlying surface can
        # itself be reversed (notably cylinders generated by extrusion).
        point = cq.Vector(surface.Value(
            (surface.FirstUParameter() + surface.LastUParameter()) / 2,
            (surface.FirstVParameter() + surface.LastVParameter()) / 2,
        ))
        radial = cq.Vector(0, point.y - y, point.z - z)
        if (face.normalAt(point).dot(radial) < 0) != bore:
            continue
        bb = bounds(face)
        matches.append({"diameter_mm": 2 * cylinder.Radius(),
                        "xmin_mm": bb[0], "xmax_mm": bb[3]})
    return matches


def _bbox_overlap(a, b):
    aa, bb = bounds(a), bounds(b)
    return all(aa[i] <= bb[i + 3] and bb[i] <= aa[i + 3] for i in range(3))


def validate(
    assembly_path: Path = DEFAULT_ASSEMBLY,
    sweep_step_deg: int = 5,
    intent: PartIntent | None = None,
) -> tuple[dict, dict]:
    if sweep_step_deg <= 0 or 360 % sweep_step_deg:
        raise ValueError("sweep step must be a positive divisor of 360")
    intent = intent or PartIntent.load(model.INTENT)
    feature = {item.name: item.constraints for item in intent.features}
    _, _, rows = read_step(assembly_path)

    link = _unique(rows, lambda row: row.path == LINK_PATH, "shoulder link occurrence")
    source_idler = _unique(
        rows,
        lambda row: row.path.startswith(MOTOR_PREFIX) and row.name == IDLER_NAME,
        "source shoulder idler occurrence",
    )
    idler_bounds = bounds(source_idler.world)
    mount_x = float(idler_bounds[0])
    axis_y = (float(idler_bounds[1]) + float(idler_bounds[4])) / 2.0
    axis_z = (float(idler_bounds[2]) + float(idler_bounds[5])) / 2.0
    placement = cq.Location(cq.Vector(mount_x, axis_y, axis_z))

    adapter_local = model.make_emergency_idler(intent).val()
    washer_local = model.make_reference_washer(intent).val()
    bolt_local = model.make_reference_bolt(intent).val()
    adapter = adapter_local.moved(placement)
    adapter_length = float(feature["support_flange"]["thickness_mm"]) + float(
        feature["rotating_pilot"]["extension_from_flange_mm"]
    )
    washer = washer_local.moved(
        cq.Location(cq.Vector(mount_x + adapter_length, axis_y, axis_z))
    )
    bolt = bolt_local.moved(placement)

    link_bore = _unique(
        _axis_cylinders(link.world, axis_y, axis_z, True),
        lambda c: c["xmin_mm"] > mount_x,
        "idler-side link bore",
    )
    pilot_surface = _unique(
        _axis_cylinders(adapter, axis_y, axis_z, False),
        lambda c: c["xmax_mm"] > link_bore["xmin_mm"] + 1e-5,
        "adapter pilot",
    )
    motor_body = _unique(rows, lambda r: r.path == MOTOR_PREFIX + "DC11_A01_DUMMY:1", "motor body")
    center_bore = _unique(
        _axis_cylinders(motor_body.world, axis_y, axis_z, True),
        lambda c: abs(c["diameter_mm"] - 3.0) < 1e-5,
        "source smooth center bore (not proof of a thread)",
    )
    bore_entry = center_bore["xmax_mm"]
    bolt_tip = bounds(bolt)[0]
    bore_overlap = max(0.0, min(bore_entry, bounds(washer)[3]) - max(bolt_tip, center_bore["xmin_mm"]))
    flange_to_link_gap = link_bore["xmin_mm"] - pilot_surface["xmin_mm"]

    retained_motor = [
        row
        for row in rows
        if row.path.startswith(MOTOR_PREFIX)
        and not any(token in row.path for token in REPLACED_TOKENS)
    ]
    motor_intersections = []
    for row in retained_motor:
        volume = _volume_intersection(adapter, row.world)
        if volume > VOLUME_TOL_MM3:
            motor_intersections.append(
                {"path": row.path, "intersection_mm3": round(volume, 9)}
            )

    # Check additions against the whole retained source assembly at its saved pose.
    # Existing source-source intersections are outside this addition review.
    addition_intersections = []
    for name, shape in (("adapter", adapter), ("washer", washer), ("bolt", bolt)):
        for row in rows:
            if row.path.startswith(MOTOR_PREFIX) and any(t in row.path for t in REPLACED_TOKENS):
                continue
            if not _bbox_overlap(shape, row.world):
                continue
            volume = _volume_intersection(shape, row.world)
            if volume > VOLUME_TOL_MM3:
                addition_intersections.append({"addition": name, "path": row.path,
                                               "intersection_mm3": volume})

    link_static_intersection = _volume_intersection(adapter, link.world)
    washer_static_intersection = _volume_intersection(washer, link.world)
    washer_to_link_distance = float(washer.distance(link.world))
    bolt_intersections = {
        "adapter_mm3": _volume_intersection(bolt, adapter),
        "washer_mm3": _volume_intersection(bolt, washer),
        "link_mm3": _volume_intersection(bolt, link.world),
        "retained_motor": [],
    }
    for row in retained_motor:
        volume = _volume_intersection(bolt, row.world)
        if volume > VOLUME_TOL_MM3:
            bolt_intersections["retained_motor"].append(
                {"path": row.path, "intersection_mm3": round(volume, 9)}
            )

    axis_start = cq.Vector(mount_x, axis_y, axis_z)
    axis_end = cq.Vector(mount_x + 1.0, axis_y, axis_z)
    sweep = []
    max_sweep_intersection = 0.0
    for angle in range(0, 361, sweep_step_deg):
        rotated_link = link.world.rotate(axis_start, axis_end, angle)
        volume = max(
            _volume_intersection(adapter, rotated_link),
            _volume_intersection(washer, rotated_link),
            _volume_intersection(bolt, rotated_link),
        )
        max_sweep_intersection = max(max_sweep_intersection, volume)
        if volume > VOLUME_TOL_MM3:
            sweep.append({"angle_deg": angle, "intersection_mm3": round(volume, 9)})

    pilot = feature["rotating_pilot"]
    fastener = feature["center_fastener"]
    washer_spec = feature["retaining_washer"]
    radial_clearance = (link_bore["diameter_mm"] - pilot_surface["diameter_mm"]) / 2
    axial_clearance = bounds(washer)[0] - link_bore["xmax_mm"]
    pilot_wall = (
        float(pilot["diameter_mm"]) - float(fastener["clearance_diameter_mm"])
    ) / 2.0

    checks = {
        "motor_intersection": not motor_intersections,
        "link_static_intersection": link_static_intersection <= VOLUME_TOL_MM3,
        "washer_static_intersection": washer_static_intersection <= VOLUME_TOL_MM3,
        "rotation_sweep": max_sweep_intersection <= VOLUME_TOL_MM3,
        "radial_clearance": radial_clearance >= 0.20 - 1e-6,
        "axial_clearance": axial_clearance >= 0.20 - 1e-6,
        "flange_support_position": abs(flange_to_link_gap) <= 1e-6,
        "source_link_matches_declared_dimensions": (
            abs(link_bore["diameter_mm"] - float(pilot["link_bore_diameter_mm"])) < 1e-6
            and abs(link_bore["xmax_mm"] - link_bore["xmin_mm"] - float(pilot["link_thickness_mm"])) < 1e-6
        ),
        "new_parts_vs_whole_source_static": not addition_intersections,
        "reference_bolt_bottom_clearance": bolt_tip - center_bore["xmin_mm"] >= 0.5,
        "reference_bolt_bore_overlap": bore_overlap >= float(fastener["thread_engagement_target_mm"]),
        "washer_retains_link": float(washer_spec["outer_diameter_mm"]) > float(
            pilot["link_bore_diameter_mm"]
        ),
        "pilot_wall": pilot_wall >= 3.0,
        "reference_bolt_clearance": (
            bolt_intersections["adapter_mm3"] <= VOLUME_TOL_MM3
            and bolt_intersections["washer_mm3"] <= VOLUME_TOL_MM3
            and bolt_intersections["link_mm3"] <= VOLUME_TOL_MM3
            and not bolt_intersections["retained_motor"]
        ),
    }
    report = {
        "status": "pass" if all(checks.values()) else "fail",
        "assembly_release": "unverified_actual_thread_and_printed_fit",
        "scope": (
            "new parts against source assembly at saved pose; sampled link rotation "
            "against adapter/washer/bolt only; not whole-arm motion, FEA, or bearing life"
        ),
        "source_assembly": str(assembly_path.resolve()),
        "source_occurrences": {
            "link": link.path,
            "replaced_idler": source_idler.path,
            "retained_motor_leaf_count": len(retained_motor),
        },
        "placement": {
            "mount_x_mm": round(mount_x, 6),
            "axis_y_mm": round(axis_y, 6),
            "axis_z_mm": round(axis_z, 6),
        },
        "dimensions": {
            "adapter_length_mm": adapter_length,
            "pilot_diameter_mm": float(pilot["diameter_mm"]),
            "link_bore_diameter_mm": float(pilot["link_bore_diameter_mm"]),
            "radial_clearance_mm": radial_clearance,
            "axial_clearance_mm": axial_clearance,
            "pilot_min_wall_mm": pilot_wall,
            "center_clearance_diameter_mm": float(fastener["clearance_diameter_mm"]),
            "measured_source_link_bore": link_bore,
            "flange_to_link_gap_mm": flange_to_link_gap,
        },
        "interference": {
            "adapter_vs_retained_motor": motor_intersections,
            "adapter_vs_link_static_mm3": round(link_static_intersection, 9),
            "washer_vs_link_static_mm3": round(washer_static_intersection, 9),
            "washer_to_link_distance_mm": round(washer_to_link_distance, 6),
            "sweep_step_deg": sweep_step_deg,
            "sweep_pose_count": 360 // sweep_step_deg + 1,
            "max_sweep_intersection_mm3": round(max_sweep_intersection, 9),
            "colliding_sweep_poses": sweep,
            "reference_bolt_intersections": bolt_intersections,
            "new_parts_vs_whole_source_static": addition_intersections,
        },
        "boltability": {
            "status": "conditional",
            "nominal_screw": fastener["nominal_screw"],
            "reference_bolt_length_mm": float(fastener["reference_bolt_length_mm"]),
            "length_formula_mm": (
                "adapter_length + washer thickness + seat_to_thread_entry_recess + measured thread engagement"
            ),
            "known_stack_before_thread_mm": round(
                bounds(washer)[3] - bore_entry, 3
            ),
            "source_smooth_bore": center_bore,
            "seat_to_bore_entry_recess_mm": round(mount_x - bore_entry, 6),
            "reference_bolt_in_smooth_bore_mm": round(bore_overlap, 6),
            "minimum_modeled_bore_overlap_mm": float(fastener["thread_engagement_target_mm"]),
            "reference_bolt_bottom_clearance_mm": round(bolt_tip - center_bore["xmin_mm"], 6),
            "thread_engagement_verified": False,
            "required_measurement": (
                "measure the actual servo center-thread diameter and usable depth; "
                "choose a bolt that cannot bottom out"
            ),
        },
        "physical_properties": model.physical_properties(intent),
        "checks": checks,
    }
    context = {
        "rows": rows,
        "link": link,
        "retained_motor": retained_motor,
        "adapter": adapter,
        "washer": washer,
        "bolt": bolt,
    }
    return report, context


def build_full_arm(context: dict) -> cq.Assembly:
    """Keep every source occurrence except the replaced shoulder idler hardware."""
    assembly = cq.Assembly(name="source_arm_with_emergency_idler_PROTOTYPE")
    for row in context["rows"]:
        if row.path.startswith(MOTOR_PREFIX) and any(t in row.path for t in REPLACED_TOKENS):
            continue
        color = cq.Color(0.35, 0.65, 0.62) if row.path == LINK_PATH else row.color
        assembly.add(row.world, name=f"source_{row.index:03d}_{row.name}", color=color)
    assembly.add(context["adapter"], name="emergency_printed_idler", color=cq.Color(0.95, 0.45, 0.10))
    assembly.add(context["washer"], name="reference_wide_washer", color=cq.Color(0.25, 0.45, 0.80))
    assembly.add(context["bolt"], name="reference_M3x12_bolt_envelope", color=cq.Color(0.20, 0.20, 0.22))
    return assembly


def export(out: Path, report: dict, context: dict) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    model_paths = model.export(out)

    check_assembly = cq.Assembly(name="emergency_center_bolt_idler_fit_check")
    for index, row in enumerate(context["retained_motor"]):
        check_assembly.add(row.world, name=f"motor_{index:02d}_{row.name}", color=row.color)
    check_assembly.add(context["link"].world, name="shoulder_to_elbow_link", color=cq.Color(0.35, 0.65, 0.62))
    check_assembly.add(context["adapter"], name="emergency_printed_idler", color=cq.Color(0.95, 0.45, 0.10))
    check_assembly.add(context["washer"], name="reference_wide_washer", color=cq.Color(0.25, 0.45, 0.80))
    check_assembly.add(context["bolt"], name="reference_M3x12_bolt_envelope", color=cq.Color(0.20, 0.20, 0.22))
    assembly_path = out / "emergency_center_bolt_idler_fit_check.step"
    check_assembly.export(str(assembly_path))

    # Separate visualization artifact; never use sectioned solids for clearance
    # acceptance or manufacture. The cut passes through the fastener axis.
    y = report["placement"]["axis_y_mm"]
    section_keep = cq.Workplane("XY").box(2000, 1000, 2000).translate((0, y - 500, 0)).val()
    section = cq.Assembly(name="VISUAL_ONLY_center_axis_section")
    for name, item in check_assembly.objects.items():
        if item.obj is None:
            continue
        cut = item.obj.intersect(section_keep)
        if cut.Volume() > VOLUME_TOL_MM3:
            section.add(cut, name=name.rsplit("/", 1)[-1], color=item.color)
    section_path = out / "emergency_center_bolt_idler_section_visual_only.step"
    section.export(str(section_path))

    full_arm = build_full_arm(context)
    full_arm_path = out / "arm_with_emergency_center_bolt_idler.step"
    full_arm.export(str(full_arm_path))
    report["full_arm_visualization"] = {
        "source_occurrences": len(context["rows"]),
        "retained_source_occurrences": len(full_arm.children) - 3,
        "replacement_occurrences": 3,
        "scope": "source mixed-servo arm at saved pose with only shoulder idler hardware replaced",
    }

    report_path = out / "validation.json"
    paths = {
        **model_paths,
        "fit_check_step": str(assembly_path.resolve()),
        "section_visual_only_step": str(section_path.resolve()),
        "full_arm_step": str(full_arm_path.resolve()),
        "validation_report": str(report_path.resolve()),
    }
    report["artifacts"] = paths
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    return paths


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assembly", type=Path, default=DEFAULT_ASSEMBLY)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--sweep-step-deg", type=int, default=5)
    parser.add_argument("--fail-on-mismatch", action="store_true")
    args = parser.parse_args(argv)
    if args.sweep_step_deg <= 0 or 360 % args.sweep_step_deg:
        raise SystemExit("--sweep-step-deg must be a positive divisor of 360")
    report, context = validate(args.assembly, args.sweep_step_deg)
    report["artifacts"] = export(args.out, report, context)
    print(json.dumps(report, indent=2))
    return 2 if args.fail_on_mismatch and report["status"] != "pass" else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
